name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          template: classic

          # Base sections
          base: header, activity, community, repositories, metadata
          base_indepth: false
          base_hireable: false
          config_timezone: America/New_York

          optimize: yes
          repositories_batch: 100

          committer_branch: main
          committer_message: "Update GitHub Metrics SVG"
          dryrun: no