name: GitHub Metrics

on:
  pull_request:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          template: classic

          # Base sections
          base: header, activity, community, repositories, metadata
          base_indepth: false
          base_hireable: false
          config_timezone: America/New_York

          # Optimize speed
          optimize: yes      # fast mode enabled
          repositories_batch: 100  # fetch repos in batches